### ISSUE TITLE
Create a production posgresql database

### ISSUE THREAD

**Issue by codypotter** [botanical-code/micans-botanicals#7]
1. Create an account on elephantsql.com
2. create a new instance (tiny turtle size is free)
3. give it a name for our store
4. For region, us-east-1
5. finish configuring it
6. inspect your database instance, note that the URL is the string we will use to connect to the database, and we have login credentials as well.
7. if you look closely at the URL, you can see that the username and password are inside that string.

We'll use this URL connection string when we hook sequelize up to the database

**Comment by knharman** [comment]
Complete!
