### ISSUE TITLE
Connect the express app to the production backend 

### ISSUE THREAD

**Issue by codypotter** [botanical-code/micans-botanicals#8]
Follow the sequelize getting started guide https://sequelize.org/docs/v6/getting-started/ 

Read carefully, because the guide gives you installation commands for all kinds of databases and different methods of connecting. We want to connect to a postgres database with a connection string. The code for connecting to the database can just go in your app.js file above the route handlers for now. 

You can get the connection string by logging into elephansql, click the database, check the details, and click the copy button next to the URL field

**Comment by knharman** [comment]
Complete!
